env:
  global:
    - CC_TEST_REPORTER_ID=<%= Rails.application.credentials.test_reporter_id %>
language: ruby
rvm:
  - 2.5.5
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT