default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/bookmarkd_development

test:
  <<: *default
  database: db/bookmarkd_test

production:
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: bookmarkd
  password: <%= Rails.application.credentials.db_password %>
  host: localhost
  port: 5432
  database: bookmarkd_production
